### ISSUE TITLE
unique-recall

### ISSUE THREAD

**Issue by yaanolja** [guillemcortes/baf-dataset#1]
Thanks for sharing a good dataset.

The unique-recall calculation(compute_statistics.py) is as follows.
recall = len(tps_rs_unique) / (len(tps_rs_unique) + len(fns_gt_unique))

I think tps_rs_unique should replaced with tps_gt_unique.

**Comment by guillemcortes** [comment]
Hi, thank you for your comment.

`tps_rs_unique` contains the number of True Positive segments of an algorithm results.
`tps_gt_unique` contains the number of True Positive segments annotated that collide with `tps_rs_unique`. The purpose of this number is to compute `TP_event_ratio`. Let me know if you need more clarification on this.

**Comment by yaanolja** [comment]
Thanks for your explanation.

Hmm... I think the denominator of recall is the number of groundtruth('unanimity' tag in cross_annotations.csv).
recall = tps_gt_unique / groundtruth_num

**Comment by guillemcortes** [comment]
Hi again, you're right. In terms of number of matches recall is `recall = len(tps_gt_unique) / (len(tps_gt_unique) + len(fns_gt_unique))`. The F1 score (in terms of number of matches) then does not make a lot of sense so I'll just remove it. I'll update the code soon. Thanks again for raising this issue.

**Comment by guillemcortes** [comment]
Hi, marking this as compleated. Find the new code version here: https://github.com/guillemcortes/baf-dataset/commit/b406cf7dafac479a5ea2806e2910dd88761cf6cb
